### ISSUE TITLE
libtextstyle is now required?

### ISSUE THREAD

**Issue by veganvelociraptor** [Frogging-Family/vkd3d-git#7]
> BISON    libs/vkd3d-shader/hlsl.tab.h
> BISON    libs/vkd3d-shader/preproc.tab.h
> bison: error while loading shared libraries: libtextstyle.so.0: cannot open shared object file: No such file or directory
> make: *** [Makefile:2902: libs/vkd3d-shader/hlsl.tab.h] Error 127
> make: *** Waiting for unfinished jobs....
> bison: error while loading shared libraries: libtextstyle.so.0: cannot open shared object file: No such file or directory
> make: *** [Makefile:2894: libs/vkd3d-shader/preproc.tab.h] Error 127
> BISON    libs/vkd3d-shader/hlsl.tab.h
> bison: error while loading shared libraries: libtextstyle.so.0: cannot open shared object file: No such file or directory
> BISON    libs/vkd3d-shader/preproc.tab.h
> make: *** [Makefile:2902: libs/vkd3d-shader/hlsl.tab.h] Error 127
> make: *** Waiting for unfinished jobs....
> bison: error while loading shared libraries: libtextstyle.so.0: cannot open shared object file: No such file or directory
> make: *** [Makefile:2894: libs/vkd3d-shader/preproc.tab.h] Error 127
> ==> ERROR: A failure occurred in build().
> Aborting...
> -> Cleanup done

Am I doing something wrong here? I tried installing libtextstyle-git from the AUR but it didn't help.

**Comment by ptr1337** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/gettext/-/issues/2

dont know, if youre using the cachyos repo, but in case you need to downgrade with "sudo pacman -S core/gettext".

ive removed the package from the repo's but it appears that it is likely wrongly packaged from archlinux, see above issue

**Comment by veganvelociraptor** [comment]
Yep, I had to downgrade it.

Thank you @ptr1337 , you're a real gem!
